### ISSUE TITLE
Can't run integration tests after java upgrade

### ISSUE THREAD

**Issue by longtimeago** [teamed/qulice#269]
Yesterday I've remove openjdk and install oracle-jdk.1.7.0.60
After that I've got:
```
[INFO] --- maven-invoker-plugin:1.6:run (default) @ qulice-maven-plugin ---
[INFO] Building: checkstyle-violations/pom.xml
[INFO] Error: JAVA_HOME is not defined correctly.
[INFO]   We cannot execute /usr/lib/jvm/java-7-openjdk-amd64/bin/java
[INFO] run script /home/ppolishchuk/pr/qulice/qulice-maven-plugin/target/it/checkstyle-violations/verify.groovy
[INFO] Running post-build script: /home/ppolishchuk/pr/qulice/qulice-maven-plugin/target/it/checkstyle-violations/verify.groovy
[INFO] ..FAILED (0.4 s)
[INFO]   The post-build script did not succeed. assert log.text.contains('LICENSE found')
       |   |    |
       |   |    false
       |   Error: JAVA_HOME is not defined correctly.
       |     We cannot execute /usr/lib/jvm/java-7-openjdk-amd64/bin/java
       |   Running post-build script: /home/ppolishchuk/pr/qulice/qulice-maven-plugin/target/it/checkstyle-violations/verify.groovy
       /home/ppolishchuk/pr/qulice/qulice-maven-plugin/target/it/checkstyle-violations/build.log
```
What I have already tried:
1) Check JAVA_HOME - it's OK
2) Restart IDEA
3) Run maven build from command line
4) Reboot PC

I understand that there is a problem executing verify.groovy script, because JAVA_HOME in traces contains old invalid path, but have no idea were it is needed

**Comment by krzyk** [comment]
@longtimeago For me it looks like a problem with `update-alternatives` or similar. It might cause problems because of lack of links between directories in the `/etc` or in the `/lib`. I install sun jdk in `/opt` and mange it by myself, so that might be an option for you also.
You could also try to set `IDEA_JDK` in your shell and then run intellij (in the same shell), or hardcode `JAVA_HOME` inside `idea.sh`

**Comment by longtimeago** [comment]
@krzyk looks like it's not reproduced anymore, thanks for your help
