### ISSUE TITLE
Sometimes qulice-checkstyle tests hang with 100% cpu usage

### ISSUE THREAD

**Issue by krzyk** [teamed/qulice#303]
Sometimes when I run ``qulice-checkstyle`` it stops working here:
```
[INFO] 
[INFO] --- maven-surefire-plugin:2.16:test (default-test) @ qulice-checkstyle ---
[INFO] Surefire report directory: /home/sg0891848/dev/tpc2/qulice/qulice/qulice-checkstyle/target/surefire-reports
[INFO] parallel='all', perCoreThreadCount=true, threadCount=4, useUnlimitedThreads=false, threadCountSuites=0, threadCountClasses=0, threadCountMethods=0

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
```

And CPU usage jumps to 100%. I assume something is wrong with running tests in parallel.

**Comment by palyuga** [comment]
@krzyk could you please capture a thread dump when it happen again?

**Comment by krzyk** [comment]
@palyuga sure

**Comment by palyuga** [comment]
@krzyk The issue reproduced on my Windows machine once, a thread dump pointed to this JVM problem: http://bugs.java.com/bugdatabase/view_bug.do?bug_id=7183450
If you have Windows too, the solution is to add "-Djava.net.preferIPv4Stack=true" to your JAVA_OPTS
But I can't check it, as I can't reproduce the issue again (miracle)

**Comment by krzyk** [comment]
@palyuga I'm using Linux most of the time (unless there is a Windows bug that needs fixing), and this bug was reported under Linux for sure

**Comment by palyuga** [comment]
@krzyk in this case i'm still waiting for a thread dump from you

**Comment by krzyk** [comment]
@palyuga Here it is https://gist.github.com/krzyk/a5d71e7ce7a0435d8be2

I recreated it without proxy (I did about 14 builds and it happened)

**Comment by palyuga** [comment]
@krzyk As we can see there are no deadlocks and the first two threads seems to be just hanging in java.io.FileInputStream.readBytes(Native Method)  (the similar IO problem was in my case, when InputStream.available() returns false). Doesn't look like a problem with quilice code. I think I can't help here/ We can close it or I'll ask to assign to someone else, as you wish.

**Comment by krzyk** [comment]
@palyuga OK, so in that case please report this issuue to MSHARED and add a comment about this problem in our project. I'm not sure where, because it is not test related @yegor256 do you have some suggestions?

**Comment by yegor256** [comment]
@palyuga I think @krzyk is right, you should report this bug to MSHARED and put the link to our source code. I think the best place is the README.md file, in the "how to contribute" section. Just say there that due to a bug in MSHARED (here is the link) you may experience build hanging, sometimes, etc. That will be it for this task.

**Comment by palyuga** [comment]
@krzyk I've took another look to the problem. I was wrong, theese two processes are waiting for output from STDERR and STDOUT of a child process spawned by Runtime.exec(), where maven-surefire-plugin tries to execute unit tests. But the process hangs with no output.

I've found a discussion about such issue with a similar thread dump: http://comments.gmane.org/gmane.comp.jakarta.turbine.maven.user/135026
So it looks like migration to maven-surefire-plugin v. 2.18 could shed light on roots of this problem. At least we should receive an exception instead of silent hanging. 

I've created an issue in jcabi-parent (https://github.com/jcabi/jcabi-parent/issues/22), so lets wait for migration.

**Comment by davvd** [comment]
@palyuga this task is not yours any more (took too long), please stop. I'll give you something else... -60 to your rating, your total score is +90

**Comment by palyuga** [comment]
@davvd we are waiting for https://github.com/jcabi/jcabi-parent/issues/22 here

**Comment by palyuga** [comment]
@krzyk now surefire-plugin 2.18.1 is used. Could you check again, does the problem occur now?

**Comment by krzyk** [comment]
@palyuga has the new parent been released and added to qulice pom?

**Comment by palyuga** [comment]
@krzyk oops, i've rushed with it. Lets wait for release)

**Comment by krzyk** [comment]
@palyuga thanks, I haven't seen this problem in a while
