### ISSUE TITLE
gradle support

### ISSUE THREAD

**Issue by ravishanker** [teamed/qulice#339]

**Comment by davvd** [comment]
@dpisarenko please go ahead with this task,it's yours

**Comment by dpisarenko** [comment]
@ravishanker  @yegor256

  1. I added a PR ( https://github.com/teamed/qulice/pull/383/ ) with the skeleton of the Qulice plugin for Gradle.
  1. It can be built by running `gradle build` inside its directory (`qulice/qulice-gradle-plugin`).
  1. The current code is written in Java, but IntelliJ Idea cannot resolve Gradle API classes because I don't know what dependency to write in `pom.xml` (for classes `org.gradle.api.`). Asked about this on StackOverflow ( http://stackoverflow.com/questions/27950384/what-are-the-maven-dependency-parameters-for-the-java-gradle-api ).
  1. Please tell me, if you agree to write the code of the Qulice plugin in Java (not in Groovy).
  1. Please tell me, how the current skeleton of the `com.qulice.gradle.QulicePlugin` class needs to be modified in order to complete this task.

**Comment by yegor256** [comment]
1. Let's discuss it after it's merged

2. OK

3. OK

4. I have nothing against Java :)

5. Let's discuss this after the pull request is merged

**Comment by dpisarenko** [comment]
@davvd Please find someone to review my PR https://github.com/teamed/qulice/pull/383 .

**Comment by dpisarenko** [comment]
@yegor256  Please tell me what else needs to be done to close this task.

**Comment by yegor256** [comment]
@dpisarenko I think we're good to close this ticket and work with sub-tasks that will be generated later @ravishanker please, close this ticket, since we implemented the skeleton of the solution. soon, we'll implement the rest and will let you know when ready.

**Comment by davvd** [comment]
there is a puzzle in this code `339-6f043704`, we'll resolve it later

**Comment by davvd** [comment]
@dpisarenko I added **30 mins** to your account, many thanks for working with the project!... added +30 to your rating, now it is equal to [+370](http://www.netbout.com/b/35089?open=rating)
