### ISSUE TITLE
XmlValidator.java:70-71: Fix all test cases to...

### ISSUE THREAD

**Issue by davvd** [teamed/qulice#348]
Puzzle `252-a79829e3` in `qulice-xml/src/main/java/com/qulice/xml/XmlValidator.java:70-71` has to be resolved: Fix all test cases to pass with formating check enabled and change default value to true.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by nhekfqn** [comment]
Just in case: as discussed with Yegor, I'll start working on tasks at 5th of January.

**Comment by yegor256** [comment]
@nhekfqn no problem, thanks for notifying

**Comment by nhekfqn** [comment]
Pull request sent https://github.com/teamed/qulice/pull/364 Please let me know if I need do anything else to close this task.

**Comment by nhekfqn** [comment]
ci build failed because qulice-findbugs has compilation warnings on openjdk6 - not sure if I should do something about it?

**Comment by yegor256** [comment]
travis build is only for information, you may ignore it

**Comment by davvd** [comment]
@nhekfqn the ticket is with you for 12 days already. If it's not finished in the next 40 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle. do not forget that you should remove the `@todo` puzzle from the source code. -30 added to your rating, at the moment it is: -30

**Comment by nhekfqn** [comment]
@davvd what is effect of my rating and what do I do to change it? It seems my mistake was not chasing you to find a reviewer, wasn't it? I've notified that I would start working on task from 5th of January, this task was assigned to me anyways. Can we fix that gap of 5 days (revert rating penalty, give me more time to finish task)? More common question: what should I do if I see task is delayed due to another person inactivity (If chasing does not help)? Should I reject task if I see it will not be closed in time to save rating?

**Comment by yegor256** [comment]
@nhekfqn create an account in www.netbout.com and give me your name there. I will share all info about your rating. In general, your job is to chase the task, until it's closed. If you fail, for any reason, you fail. Looks like you understand it already. If you see that your delay is caused by someone else and all your attempts to speed things up fail, address your comments to me or @davvd, asking to resolve the situation. Be aggressive, it usually helps.

**Comment by nhekfqn** [comment]
@yegor256 my netbout account name: nhekfqn

**Comment by nhekfqn** [comment]
@davvd  should I notify that PR https://github.com/teamed/qulice/pull/364 has been merged?

**Comment by yegor256** [comment]
@nhekfqn it's better to do so, yes. Check your netbout account, you should see some data there

**Comment by nhekfqn** [comment]
@davvd https://github.com/teamed/qulice/pull/364 has been merged. Can I get payment and we close the ticket now?

**Comment by davvd** [comment]
> @davvd what is effect of my rating and what do I do to change it? It seems my mistake was not chasing you to find a reviewer, wasn't it? I've notified that I would start working on task from 5th of January, this task was assigned to me anyways. Can we fix that gap of 5 days (revert rating penalty, give me more time to finish task)? More common question: what should I do if I see task is delayed due to another person inactivity (If chasing does not help)? Should I reject task if I see it will not be closed in time to save rating?

@nhekfqn no problem, thanks for letting me know

**Comment by nhekfqn** [comment]
@davvd @todo puzzle has been removed from code, in master branch https://github.com/teamed/qulice/blob/master/qulice-xml/src/main/java/com/qulice/xml/XmlValidator.java Please close the ticket.

**Comment by nhekfqn** [comment]
@davvd Please close the ticket.

**Comment by yegor256** [comment]
@nhekfqn this article should help: http://www.yegor256.com/2015/01/15/how-to-cut-corners.html

When you can't complete the ticket on time because of some dependency (another person not answering, another ticket is not solved, etc) - just say that you need more time.

**Comment by nhekfqn** [comment]
@davvd I need more time for you to close this ticket please ; )

**Comment by davvd** [comment]
> @davvd I need more time for you to close this ticket please ; )

@nhekfqn take your time, I'm aware that we're waiting here

**Comment by davvd** [comment]
Done, thanks all, closing..

**Comment by davvd** [comment]
@nhekfqn Thanks for your contribution, **30 mins** was added to your account, payment ID is `50344390`; +30 added to your rating, at the moment it is: [-30](http://www.netbout.com/b/35123?open=rating)
