### ISSUE TITLE
Method declaration formatting

### ISSUE THREAD

**Issue by caarlos0** [teamed/qulice#457]
The method calling formatting for lines with more than 80c is:

```java
this.work(
  lot,
  of,
  parameters,
  just,
  to,
  exemplify
)
```

I think that we should use this same pattern for method declaration:

```java
public boolean flush(
  final int job, 
  final int partition,
  final Runnable callback
) throws IOException {
```

**Comment by davvd** [comment]
@yegor256 please do something about this issue

**Comment by yegor256** [comment]
@caarlos0 well, method calls must be formatted like this, because we can nest them. We can have many levels of method calls. In case of method declaration - there is only one level, always. No need to format it anyhow, there is basically no harm done, if it's formatted the "wrong" way. See my point?

**Comment by caarlos0** [comment]
@yegor256 yes, you're right. thanks
