### ISSUE TITLE
Qulice does not enforce any of "Empty Code" PMD rules

### ISSUE THREAD

**Issue by mkordas** [teamed/qulice#544]
There are lots of rules in PMD ['empty' ruleset](https://pmd.github.io/pmd-5.4.1/pmd-java/rules/java/empty.html), but they are not mentioned in Qulice's PMD configuration.

I would excpect all of them being enforced by Qulice.

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk I added `bug` tag to this ticket

**Comment by davvd** [comment]
@mkordas thanks for the report, I topped your acc for 15 mins, payment ID `567d39d6238bc80a06000077`

**Comment by krzyk** [comment]
@davvd assign @prahladyeri please

**Comment by prahladyeri** [comment]
@krzyk I'm looking into this.

**Comment by prahladyeri** [comment]
@mkordas I have one query:

> There are lots of rules in PMD 'empty' ruleset, but they are not mentioned in Qulice's PMD configuration

But many of the `empty` ruleset violations are already being by the `checkstyle-validator` plugin. For instance, If I try to place an [empty](https://pmd.github.io/pmd-5.4.1/pmd-java/rules/java/empty.html#EmptyCatchBlock) `catch{}` block, `checkstyle-validator` will fail with this message:

[ERROR] /src/test/java/com/qulice/checkstyle/CheckstyleValidatorTest.java[92]: Must have at least one statement. (EmptyBlockCheck)

Again, the same will happen if I place an [empty](https://pmd.github.io/pmd-5.4.1/pmd-java/rules/java/empty.html#EmptyWhileStmt) `while(a = b){}` statement:

[ERROR] /src/test/java/com/qulice/checkstyle/CheckstyleValidatorTest.java[90]: Must have at least one statement. (EmptyBlockCheck)

So the question is, do we really need two different validators in our system that basically do the same thing?

**Comment by mkordas** [comment]
@prahladyeri In general there is overlap, but are you sure that every 'empty' PMD rule is covered by Checkstyle rule? For example is there replacement for `EmptyStatementNotInLoop`? 
Moreover Checkstyle is buggy tool because it does manual operations on AST syntax trees and I would be not surprised by false-negatives even in such simple checks.

**Comment by davvd** [comment]
> @davvd assign @prahladyeri please

@krzyk OK @prahladyeri please go ahead, this task is yours

**Comment by prahladyeri** [comment]
@mkordas @krzyk 
The `EmptyStatementNotInLoop` is indeed validated by the checkstyle. For example, If you just leave a single semi-colon (`;`) on a line, it will throw this:

    [ERROR] /src/test/java/com/qulice/checkstyle/CheckstyleValidatorTest.java[90]: Empty statement. (EmptyStatementCheck)

I'll still go ahead and implement the `pmd` unit test cases, if you are concerned about the `checkstyle` tool being buggy.

**Comment by prahladyeri** [comment]
@mkordas @krzyk 
After some digging into code, I think there is something major wrong with the `qulice-pmd` plugin, because all the empty code PMD rules check should already be happening, but they aren't. All empty rules are part of the [basic](http://pmd.sourceforge.net/pmd-4.3.0/rules/basic.html) ruleset which we are already defining in the [ruleset.xml](https://github.com/teamed/qulice/blob/ebf85bd3162241d029b6796da98e91d2d08228cc/qulice-pmd/src/main/resources/com/qulice/pmd/ruleset.xml):

    <rule ref="rulesets/java/basic.xml">
        <exclude name="AvoidThreadGroup"/>
    </rule>

And this rule is assuredly checked in the `SourceValidator` class which is referred to by the `PMDValidator` test run:

    public SourceValidator(final Environment env) {
        this.listener = new PmdListener(env);
        this.config = new PMDConfiguration();
        this.config.setRuleSets("com/qulice/pmd/ruleset.xml");
        final Report report = new Report();
        report.addListener(this.listener);
        this.context.setReport(report);
    }

Now, the only reason I could think of that why the `basic.xml` ruleset isn't applied is that priority isn't defined that, and a minimum priority of `5` is needed in order for the `SourceValidator` to be processed:

    private void validateOne(final DataSource source) {
        final RuleSetFactory factory = new RuleSetFactory();
        // @checkstyle MagicNumber (1 line)
        factory.setMinimumPriority(RulePriority.valueOf(5));
        PMD.processFiles(
            this.config,
            factory,
            new LinkedList<DataSource>(Collections.singleton(source)),
            this.context,
            Collections.<Renderer>emptyList()
        );
    }

But I don't understand how do I test this scenario and make sure its because of that? If I remove that priority rule for testing, it won't work because when I build `qulice`, it uses a different version of `qulice-pmd` than the one I've local modified for testing?

**Comment by krzyk** [comment]
@prahladyeri you have two options to test the new code, use `PMDValidatorTest` (if you want to test single rule, and it works great from IDE) or create new IT test in `qulice-maven-plugin/src/it/` (this one is for larger tests, it basically runs qulice against given source tree).

**Comment by krzyk** [comment]
@prahladyeri why do you say that empty rules are part of basic ones? I don't recall that PMD would load one rule from other xml files. See all the rules in PMD: https://github.com/pmd/pmd/tree/master/pmd-java/src/main/resources/rulesets/java, basic.xml doesn't include empty.xml.

**Comment by krzyk** [comment]
@prahladyeri also, we have 3 custom rules defined in our ruleset.xml file and all of them have priority set to `3`, and they are not ignored in anyway.

**Comment by prahladyeri** [comment]
@mkordas @krzyk 
I think I just found out the source of this trouble! The missing `priority` is indeed the culprit here. I don't know why the 3 custom rules defined with priority `3` are working, but the missing priority in `basic.xml` ruleset does play a role in not triggering the "Empty Code" PMD rules. To verify this, just add a priority `7` to `/com/qulice/pmd/ruleset.xml` as follows:

    <rule ref="rulesets/java/basic.xml">
        <exclude name="AvoidThreadGroup"/>
        <priority>7</priority>
    </rule>

If you add the priority tag and build, it will magically start validating all the "Empty Code" checks! For instance, after changing the above, my build failed for the following two files which had the empty code block issues:

    Failed tests: 
      PMDValidatorTest.forbidsUnnecessaryFinalModifier:219->validatePMD:304 
    Expected: a string containing "Unnecessary final modifier"
         but: was "ERROR - /src/main/java/Other.java[6-6]: Document empty method body (UncommentedEmptyMethodBody)

    ERROR - /src/main/java/foo/UselessParentheses.java[8-8]: Useless parentheses. (UselessParentheses)

@krzyk 
> why do you say that empty rules are part of basic ones?

But If you read this pmd's [sourceforge docs](http://pmd.sourceforge.net/pmd-4.3.0/rules/basic.html) for `basic.xml`, it already includes all the empty rulesets including `EmptyCatchBlock`, `EmptyIfStmt`, `EmptyWhileStmt`, `EmptyTryBlock`, `EmptyFinallyBlock`, etc. etc. So, `basic.xml` should have us covered for all empty code rules, there is no need for any other ruleset.

**Comment by krzyk** [comment]
@prahladyeri you linked to old pmd page (for 4.3) release, new one is here https://pmd.github.io/, the separated empty rules from basic ones

**Comment by prahladyeri** [comment]
@krzyk Indeed, the new version already has an `empty.xml` ruleset file. S, do we just import this file into qulice-pmd project and configure it in `SourceValidator` ?

**Comment by krzyk** [comment]
@prahladyeri Yes, add empty.xml to the rulesete.xml and create a integration test that validates that we report all the errors. (previously we didn't have this check so when we upgraded from  PMD 4.x to 5.x we lost those rules). I don't think you need to do anything in `SourceValidator`.

As for the priority, please report a separate bug, with a list of rules that we ignore and their priorities.

**Comment by prahladyeri** [comment]
@krzyk I don't know what's happening, but even after I added `empty.xml`, the PMD violations aren't triggered.  For example, I added the following:

    if (1==2) {
        //just a comment!
    }

It triggers a `EmptyBlockCheck` violation which is a `CheckStyle` violation. But there is no PMD violation.

**Comment by krzyk** [comment]
@prahladyeri checkstyle is called before PMD, so you have to find a rule that exists in PMD but not in checkstyle

**Comment by prahladyeri** [comment]
@krzyk There isn't any rule in [empty ruleset](https://pmd.github.io/pmd-5.4.1/pmd-java/rules/java/empty.html) that isn't already handled by `checkstyle`. Checkstyle throws the generic exception, `EmptyBlockCheck`, whereas it is termed as `EmptyCatchBlock`, `EmptyIfStmt`, `EmptyWhileStmt`, etc. in case of PMD.

Not only that, but I also tried rearranging the modules in `pom.xml` so that pmd is checked before checkstyle, but still pmd did not raise any violations:

    <modules>
        **<module>qulice-pmd</module>**
        <module>qulice-ant</module>
        <module>qulice-checkstyle</module>
        <module>qulice-codenarc</module>
        <module>qulice-findbugs</module>
        <module>qulice-maven-plugin</module>
        <module>qulice-spi</module>
        <module>qulice-xml</module>
        <module>qulice-gradle-plugin</module>
    </modules>

**Comment by krzyk** [comment]
@prahladyeri Hmm, maybe you would need to find a case where checkstyle check is buggy, maybe there is some that PMD will catch and checkstyle not. Have you tried all of PMD checks?

As for order of PMD/Checkstyle, it is determined not by module order but by `DefaultValidatorsProvider`, you can change order there, but please don't commit changed order.

**Comment by prahladyeri** [comment]
@krzyk I managed to test all the PMD "Empty" violations. After adding `empty.xml` to the ruleset, I've also added an integration test class `PMDEmptyTest` along with a bunch of resources to verify that each one of the rules mentioned in the original link is tested, namely:

- EmptyCatchBlock.java
- EmptyFinallyBlock.java
- EmptyIfStmt.java
- EmptyInitializer.java
- EmptyStatementBlock.java
- EmptyStatementNotInLoop.java
- EmptyStaticInitializer.java
- EmptySwitchStmt.java
- EmptySynchronizedBlock.java
- EmptyWhileStmt.java

@mkordas Please check whether this resolves your issue.

**Comment by krzyk** [comment]
@prahladyeri please provide PR # here also

**Comment by prahladyeri** [comment]
@krzyk I've updated PR #561.

**Comment by prahladyeri** [comment]
@mkordas Please review and close if this resolves the issue.

**Comment by mkordas** [comment]
@prahladyeri there is another reviewer, but approach is good, thanks

**Comment by prahladyeri** [comment]
@mkordas PR #561 fixes this, last build succeeded. Please close if this resolves the issue.

**Comment by mkordas** [comment]
@prahladyeri I will close this just after successful merge

**Comment by prahladyeri** [comment]
@mkordas Is there a due process to disagree with what the second reviewer wants changed? PR #561 fixes what issue you have raised and since you are the owner of this case, only you can determine whether to accept my solution or not. What would you like to say about @krzyk 's comment on PR #561?

**Comment by krzyk** [comment]
@prahladyeri The process is that there are two gateways (not votes) first the code is checked by code reviewer and after that architect will check it, only if both of them say that the code can be merged it will be merged. If the code is not merged then issue creator can't close it, because it didn't solve his/her problem (unless he/she decides this is not an issue anymore).

**Comment by mkordas** [comment]
@prahladyeri as @krzyk said I can only close the issue when PR will be merged

**Comment by krzyk** [comment]
@prahladyeri please do not name pull requests (or commits) using github syntax "fixes #...", as issue creator should be the one that closes the issue.

**Comment by prahladyeri** [comment]
@krzyk Sorry, I'll keep that in mind for future.
@mkordas This got auto-closed as I used the github syntax while committing (`fixes #544`). Feel free to reopen and assess.

**Comment by mkordas** [comment]
@prahladyeri I don't have reopen button unfortunately, but I'm fine with proposed solution, thanks!

**Comment by davvd** [comment]
@rultor @mkordas please take a look, rultor closed it automatically

**Comment by mkordas** [comment]
@prahladyeri thanks!

**Comment by davvd** [comment]
@mkordas there is a puzzle in this code `544-c37b2cc3`/#596, we'll resolve it later

**Comment by davvd** [comment]
@prahladyeri **30 mins** was added to your account, many thanks for your contribution (payment 74033647)! The task took 240 hours and 17 mins.... +30 added to your rating, at the moment it is: [+120](http://www.netbout.com/b/36189?open=rating)

**Comment by 0pdd** [comment]
@mkordas the only puzzle [#1116](https://github.com/yegor256/qulice/issues/1116) is solved here.
