### ISSUE TITLE
Prohibit usage of plain JUnit assertions

### ISSUE THREAD

**Issue by mkordas** [teamed/qulice#646]
For consistency reasons Qulice should not allow JUnit assertions from the following families:
* `org.junit.Assert.assert*`
* `junit.framework.Assert.assert*`

I'd expect Checkstyle or PMD violation on every such assertion. However, `Assert.fail()` should remain allowed.

Rationale is in http://www.yegor256.com/2014/04/28/xml-xpath-hamcrest-matchers.html:
> Hamcrest is my favorite instrument in unit testing. It replaces the JUnit procedural assertions of `org.junit.Assert` with an object-oriented mechanism. 

Moreover, I've seen mixed assertions in some projects which introduces confusion which one to use.

**Comment by krzyk** [comment]
@mkordas good idea

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by krzyk** [comment]
@davvd this is not postponed

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk I tagged this as "bug"

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk right, I added "postponed" label

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk I will ask somebody else to pick this up

**Comment by davvd** [comment]
> @davvd this is not postponed

@krzyk right, I removed "postponed" tag

**Comment by krzyk** [comment]
@davvd assign @vkuchyn

**Comment by davvd** [comment]
> @davvd assign @vkuchyn

@krzyk OK @vkuchyn please proceed, this task is yours

**Comment by davvd** [comment]
@mkordas thanks for tis bug, I topped your account for 15 mins, transaction `56ab668ea85909434800019e`

**Comment by vkuchyn** [comment]
@krzyk Hi, I stuck on the final stage. After all fixes, try to build whole project in my feature branch `qulice-maven-plugin` fails. Reason is 
`[INFO] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.qulice:qulice-maven-plugin:1.0-SNAPSHOT:check (default) on project pom-xpath-validator-violations: Failure
....
[INFO] Caused by: com.qulice.spi.ValidationException: pom.xml don't match the xpath query [/pom:project/pom:dependencies/pom:dependency[pom:artifactId='commons-io']/pom:version[.='1.2.5']/text()]`
I am confused as far as I didn't touch any file in module 'qulice-maven-plugin' 
Maven command - as mentioned on the start page is 
`mvn clean install -Pqulice`  
I hope, you can help or shall I report an issue? Cause, it is blocker for me. 
Thx

**Comment by vkuchyn** [comment]
@krzyk  I tried to push to check builds on CI - having the same problems https://ci.appveyor.com/project/yegor256/qulice/build/456
So this is not local issue. Still have no idea how to fix it.

**Comment by vkuchyn** [comment]
@krzyk Well,  I figured out what went wrong.
An old test in /src/test/java/com/qulice/plugin/alpha/MainTest.java uses old style assertions, so that's why test failed. 
I have a question for future - what is the best way to manage such situation? I cannot close ticket - pull request fails. From other side cannot report new bug, because problems only in my local branch

**Comment by vkuchyn** [comment]
@davvd please see #665

**Comment by krzyk** [comment]
@vkuchyn you just fix it, or if it is a big change you create a todo puzzle (see http://www.yegor256.com/2009/03/04/pdd.html)

**Comment by vkuchyn** [comment]
@krzyk Thank you for answer. So I can ignore old test that fails (for me it means my changes crashed the system but de facto, this seems to be fragility of test), make todo, report a ticket like "fix test" with description. Is it okey behaviour?

**Comment by krzyk** [comment]
@vkuchyn you could ignore an old test, but it should be only a last resort. Specifically in qulice we introduce very often rules that make some parts of the old code fail, we should fix that, if the change is small and we know how to do it.
If the change is bigger, you ignore that part of the code and create a todo (you don't report a bug).
Bug reports are for things that are not related to your changes.

**Comment by vkuchyn** [comment]
@krzyk thanks

**Comment by davvd** [comment]
> @davvd please see #665 

@vkuchyn thanks, will take a look

**Comment by vkuchyn** [comment]
@mkordas Fixed at #665

**Comment by mkordas** [comment]
@vkuchyn thx

**Comment by vkuchyn** [comment]
@davvd Pls, mark ticket as closed and proceed with payment. Thank you

**Comment by davvd** [comment]
@vkuchyn Thanks for your contribution, **30 mins** was added to your account, payment ID is `77011445`, 264 hours and 58 mins spent total; +30 to your rating, your total score is [+45](http://www.netbout.com/b/36353?open=rating)
