### ISSUE TITLE
Enforce usage of diamond operator

### ISSUE THREAD

**Issue by mkordas** [teamed/qulice#715]
Qulice runs on Java 7 only, so let's add a check to enforce diamond operator usage wherever possible.

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk I added `bug` tag to this ticket

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk right, I added "postponed" label

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk got it, someone else will be assigned soon

**Comment by krzyk** [comment]
@davvd this is not postponed

**Comment by krzyk** [comment]
@davvd assign @vkuchyn

**Comment by krzyk** [comment]
@vkuchyn maybe https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/master/sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/DiamondOperatorForVariableDefinitionCheck.java check could be reused for that

**Comment by davvd** [comment]
> @davvd this is not postponed

@krzyk got it, "postponed" tag removed from here

**Comment by davvd** [comment]
> @davvd assign @vkuchyn 

@krzyk done. @vkuchyn the task is yours, please go ahead

**Comment by davvd** [comment]
@mkordas thanks a lot for reporting, **15 mins** added to your acc, pmt ID `56e142d3e4010602540001f8`

**Comment by davvd** [comment]
> @davvd fixed in #749, need review

@vkuchyn thank you

**Comment by vkuchyn** [comment]
@mkordas merged in #749. Please, close the issue

**Comment by mkordas** [comment]
@vkuchyn thx

**Comment by davvd** [comment]
@mkordas there is a puzzle in this code `715-04710633`/#752, we'll resolve it later

**Comment by davvd** [comment]
@vkuchyn Thanks for your contribution, **30 mins** was added to your account, payment ID is `80471641`, 96 hours and 15 mins spent total... +30 added to your rating, at the moment it is: [+180](http://www.netbout.com/b/36353?open=rating)

**Comment by vkuchyn** [comment]
@davvd thank you for payment. I have question about velocity. According to your policy speed is measuring from time of assignment ([3.10.2016 10:51AM GMT+2](https://github.com/teamed/qulice/issues/715#event-584548726)) to payment moment ([3.15.2016 11:43 AM GMT+2](https://github.com/teamed/qulice/issues/715#issuecomment-196743813)). After calculation we get 96 hours and 15 minutes. 
If calculate difference from  time of assignment ([3.10.2016 10:51AM GMT+2](https://github.com/teamed/qulice/issues/715#event-584548726)) to issue closing moment ([3.12.2016 9:59 AM GMT+2](https://github.com/teamed/qulice/issues/715#event-587312013)) and it will be 47 hours and 8 minutes. 
If imagine that I would done issue immediate the speed from assignment to payment would take 49 hours and 7 minutes.
The question is - how I reduce time from moment of issue closed to payment moment? Otherwise, developer loses motivation to fix issue at first 3 days - in any case, payment period may take long time and no bonuses will be provided.

**Comment by davvd** [comment]
> @davvd thank you for payment. I have question about velocity. According to your policy speed is measuring from time of assignment ([3.10.2016 10:51AM GMT+2](https://github.com/teamed/qulice/issues/715#event-584548726)) to payment moment ([3.15.2016 11:43 AM GMT+2](https://github.com/teamed/qulice/issues/715#issuecomment-196743813)). After calculation we get 96 hours and 15 minutes. 
> If calculate difference from  time of assignment ([3.10.2016 10:51AM GMT+2](https://github.com/teamed/qulice/issues/715#event-584548726)) to issue closing moment ([3.12.2016 9:59 AM GMT+2](https://github.com/teamed/qulice/issues/715#event-587312013)) and it will be 47 hours and 8 minutes. 
> If imagine that I would done issue immediate the speed from assignment to payment would take 49 hours and 7 minutes.
> The question is - how I reduce time from moment of issue closed to payment moment? Otherwise, developer loses motivation to fix issue at first 3 days - in any case, payment period may take long time and no bonuses will be provided.

@vkuchyn there is no way to be exact in this area. we know that the ticket is closed only when we pay for it. what happens before that - we have no idea and can't control. that's why, when paid it's done.
