### ISSUE TITLE
There is a newer version of com.puppycrawl.tools:checkstyle dependency

### ISSUE THREAD

**Issue by darkled** [teamed/qulice#763]
There is a newer version 6.17. I think qulice has to use the latest one. Please pay your attention that the abstract class `Check` is deprecated in this version.

**Comment by krzyk** [comment]
@darkled what are the features that we could use from that version of checkstyle?

**Comment by darkled** [comment]
@krzyk the list is [here](http://checkstyle.sourceforge.net/releasenotes.html). Don't we need support of java 9 and plenty of bug fixes?

**Comment by krzyk** [comment]
@darkled Usually we don't do simple updates, unless they are bundled into bigger tasks (e.g. upgrading multiple dependencies, adding new check that exists in new version only, or fixing a problem in qulice that was already fixed in newer dependency version) . This is to avoid burning project resources.

**Comment by darkled** [comment]
@krzyk ok, no problem. Thanks for your time :)
