### ISSUE TITLE
Create UseStringIsEmpty check

### ISSUE THREAD

**Issue by krzyk** [teamed/qulice#801]
String has a method `isEmpty()` that should be used instead of `size()`:
1. `data.size() > 0` (should be `!data.isEmpty()`)
2. `data.size() == 0` (should be `data.isEmpty()`)
3. `data.size() < 1` (should be `data.isEmpty()`)
4. `data.size() >= 1` (should be `!data.isEmpty()`)

This is a very similar case to [UseCollectionsIsEmpty](https://pmd.github.io/pmd-5.5.1/pmd-java/rules/java/design.html#UseCollectionIsEmpty).

Please add such check, preferably using PMD checks.

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk tagged this issue with "bug"

**Comment by davvd** [comment]
@krzyk many thanks for the bug report, I added 30 mins to your acc, transaction `97957774`

**Comment by amihaiemil** [comment]
@krzyk can you assign this to me?

**Comment by krzyk** [comment]
@amihaiemil I could try, let's see if davvd will allow me :)

**Comment by krzyk** [comment]
@davvd assign @amihaiemil

**Comment by davvd** [comment]
> @davvd assign @amihaiemil 

@krzyk too many tasks (3) are active in the project already, can't assign new ones

**Comment by krzyk** [comment]
@davvd assign @amihaiemil

**Comment by davvd** [comment]
> @davvd assign @amihaiemil

@krzyk OK @amihaiemil please proceed, this task is yours

**Comment by krzyk** [comment]
@amihaiemil I assume you noticed that you were assigned? :)

**Comment by amihaiemil** [comment]
@krzyk Yes, today I started looking into it.

I was thinking whether to extend ``UseCollectionsIsEmpty`` or not, since most methods would be the same; only ``appliesToClassName(String name)`` and ``getComparisonTargets()`` would differ, from what I can tell.

**Comment by amihaiemil** [comment]
@krzyk I think I'll make it independent to avoid backward compatibility issues in the future, if the guys from pmd decide to change  ``UseCollectionsIsEmpty``

**Comment by amihaiemil** [comment]
@krzyk Im not an expert in PMD, but should it not look for instance variables? I can pretty much make it work, but if I say ``this.somestring.length()``, then it won't see it... if I simply say ``somestring.length()`` then it's ok.

The same happens with other rules, e.g. ``InefficientEmptyStringCheckRule``, which is supposed to forbid ``String.trim().length()``, saying it's inefficient...  if you say ``this.somestring.trim().length()`` it won't see it.

**Comment by krzyk** [comment]
@amihaiemil yes it should work for instance as well as local variables

**Comment by amihaiemil** [comment]
@krzyk i suppose it still applies, but just to be sure: ``somestring`` is an instance variable, but it wont see the thing if I specify ``this``, thats the issue. I'll  look into it more

**Comment by amihaiemil** [comment]
@krzyk I did some research, read documentation and followed instructions from [here](http://pmd.sourceforge.net/pmd-4.3/howtowritearule.html) on how to write a rule... 

However, as I see, even existing rules such as [UseCollectonsIsEmpty](https://pmd.github.io/pmd-5.5.1/pmd-java/rules/java/design.html#UseCollectionIsEmpty) and [InefficientEmptyStringCheckRule](https://pmd.github.io/pmd-5.3.2/pmd-java/apidocs/net/sourceforge/pmd/lang/java/rule/strings/InefficientEmptyStringCheckRule.html) are quite supperficial:

1) They do not see the mistake if you start the line with ``this.``... so for instance if you say ``this.collection.size() > 0`` it won't complain.
2) If you have a chain of methods then also it won't work, only if you have one method. 

I wrote a rule very similar to the collections one (it's quite the same, only that I compare the image with ``length`` instead of ``size`` and the type with ``String`` instead of ``Collection``) but it is superficiall also, as explained above. 

Trouble is I cannot find the appropriate API to handle this - I'm not even sure it exists. I can iterate over the ``PrimaryExpression``'s suffix children, but I cannot check if one is a method call or not; I can see by debugging that a ``Node`` has a ``firstToken`` attribute, which I would like to check, but I cannot find any method that returns it. etc. 

So, the rule I wrote works the same as [UseCollectionsIsEmpty](https://pmd.github.io/pmd-5.5.1/pmd-java/rules/java/design.html#UseCollectionIsEmpty). If you say 

``somestring.length() > 0`` - this string can be any kind of variable, but don't prefix it with ``this.``, it won't work then

``someMethodThatReturnsString().length() > 0`` - also works, but if you prefix it with ``this.``, or have a chain of method calls then it does not work.

What do you think? Should I make PR with this, is it good enough (since other rules are the same)? Or should I let someone else take this?

**Comment by krzyk** [comment]
@amihaiemil Yes, such rule is good enough, you can always add a *todo* to extend it with `this.` and method chain handling (if it is possible). Or if you are sure it is not possible then don't add one.

**Comment by amihaiemil** [comment]
@davvd PR #811 is for this

**Comment by amihaiemil** [comment]
@krzyk I added todo for ``this``. 

I figured you don't need method chaning at all, since it checks that the first one should return a ``String`` and if that's the case then the following methods would be String-related..so for instance if you do ``getString().getBytes().length == 0``, length is called on bytes array, but it's still that String and you could say ``getString().isEmpty()`` - it's still logically correct.

**Comment by davvd** [comment]
> @davvd PR #811 is for this

@amihaiemil thanks for that

**Comment by amihaiemil** [comment]
@davvd I need more time

**Comment by davvd** [comment]
> @davvd I need more time

@amihaiemil sure, take your time

**Comment by krzyk** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/teamed/qulice/issues/801#issuecomment-385071188))

@krzyk Job [#801](https://github.com/teamed/qulice/issues/801) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by krzyk** [comment]
@0crat assing @amihaiemil

**Comment by 0crat** [comment]
> @0crat assing @amihaiemil  ([here](https://github.com/teamed/qulice/issues/801#issuecomment-385071974))

@krzyk Can't understand "assing", try one of these:
  - `assign` Assign a performer to this issue
  - `boost` Set a boost for the job
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Close the order and remove this job from scope
  - `pay` Pay a user some extra cash
  - `quality` Review a task
  - `resign` Resign from this issue
  - `status` Check the status of the job
  - `version` Print current version of the bot
  - `wait` Register an impediment for a job

**Comment by krzyk** [comment]
@0crat assign @amihaiemil

**Comment by 0crat** [comment]
> @0crat assign @amihaiemil ([here](https://github.com/teamed/qulice/issues/801#issuecomment-385072378))

@krzyk The job [#801](https://github.com/teamed/qulice/issues/801) assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/C3T49A35L/1171968171); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by krzyk** [comment]
@amihaiemil You've got it implemented, I just need few fixes in the PR (#811) you provided 2 years ago :)

**Comment by amihaiemil** [comment]
@krzyk sure, I'll fix it today :)

**Comment by amihaiemil** [comment]
@krzyk PR was merged just now, this Issue can be closed :D

**Comment by krzyk** [comment]
@amihaiemil thanks

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
The job [#801](https://github.com/teamed/qulice/issues/801) is now out of scope

**Comment by 0pdd** [comment]
@krzyk the puzzle [#950](https://github.com/teamed/qulice/issues/950) is still not solved.

**Comment by 0pdd** [comment]
@krzyk 2 puzzles [#1000](https://github.com/teamed/qulice/issues/1000), [#999](https://github.com/teamed/qulice/issues/999) are still not solved; solved: [#950](https://github.com/teamed/qulice/issues/950).

**Comment by 0pdd** [comment]
@krzyk 2 puzzles [#1016](https://github.com/teamed/qulice/issues/1016), [#999](https://github.com/teamed/qulice/issues/999) are still not solved; solved: [#1000](https://github.com/teamed/qulice/issues/1000), [#950](https://github.com/teamed/qulice/issues/950).

**Comment by 0pdd** [comment]
@krzyk all 4 puzzles are solved here: [#1000](https://github.com/teamed/qulice/issues/1000), [#1016](https://github.com/teamed/qulice/issues/1016), [#950](https://github.com/teamed/qulice/issues/950), [#999](https://github.com/teamed/qulice/issues/999).
