### ISSUE TITLE
The Javadoc comments are (sometimes) redundant noise

### ISSUE THREAD

**Issue by pa9ey** [teamed/qulice#824]
Two things first:
- Sorry for suddenly bombarding you all with these kinds of issues! (I think I have one more and then I'll shut up.)
- This issue doesn't apply to projects that actually require good, complete, online docs. (So I'm not suggesting you get rid of the *option* of enforcing this stuff.)

But with those caveats in place:

I'm particularly talking about the method and attribute comments.

- They often end up just repeating the code so they add nothing.
- They actually clutter and lengthen the file making it harder to mentally process, not easier.
- Qulice cannot guarantee that the comments are actually good and useful so review is still required anyway.

**Would it be possible to have a way of not requiring these doc comments if your project doesn't need to actually *publish* docs?**

In cases like that, if the classes are short and to the point and everything is well-named I don't think the comments be needed in the code itself. Also, if a project has terse, spec-like, well-written tests then usage of the class will be documented (for the developer) anyway.

(This issue was migrated from here: https://github.com/yegor256/eo/issues/107)

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by krzyk** [comment]
@pa9ey Qulice doesn't allow optional enforcement. The basic idea is that, if a project uses qulice everyone knows what kind of enforcement is there.

There are some projects that publish javadocs and some that are private and don't publish them to the outside world (but still use them internally).

I would agree that private methods most of the time don't need those, but public methods on the other hand it is good to have those documented.

@yegor256 What do you think about javadoc enforcement?

**Comment by pa9ey** [comment]
@krzyk I knew it would be a bit controversial. I just thought I'd give it a go. Mostly I'm beginning to like the fact that Qulice is very opinionated. So I might have to just suck it up regarding the Javadoc stuff. :)

**Comment by Glusk2** [comment]
It is a good thing when someone or something is telling you to document your code. However, every single piece of code that is written is not meant to be documented.


Qulice's greatest strength is also it's greatest weakness and you may end up with this kind of docs:

> ### Listing 1. Typical worthless Javadoc
> ```
>     /**
>       * Represents a command history
>       */
>     public class CommandHistory {
>         /**
>          * Get the command history for a given user
>          */
>         public static CommandHistory getCommandHistory(String user) {
>         . . .
>         }
>     }
> ```

[*from **Java theory and practice: I have to document THAT?** by **Brian Goetz***](https://www.ibm.com/developerworks/library/j-jtp0821/j-jtp0821-pdf.pdf)

Of course, a natural thing to do then is to think what you're doing wrong in the code that you can't document it in a more meaningful way which in turn leads to re-factoring and better code base overall.

**Comment by pa9ey** [comment]
@Glusk2 Really interesting stuff! What would you say then? That the Javadoc comments should be there, but that if they're simply parroting the code you've missed an opportunity? Or do you agree that some Javadoc comment simply don't need to be there?

**Comment by Glusk2** [comment]
Not only is it pointless to write _useless docs_ but also extremely dangerous. Once qulice is happy that you've done your job and commented a block of code, for it, the story is finished. It doesn't care about any modifications (apart from method/class/interface signatures and some best practices checks; but no content checks, which would be hard to implement anyway) you might have done to your code which could render your docs obsolete.

Aren't, for example, unit tests also (but not only!) meant to be a reference, something you can quickly glaze at to see working examples of library usage? Commenting them with javadocs only defeats this purpose. And if you take a look at some of those comments, it's more or less _useless docs_. Still, sometimes it's more convenient to lookup javadocs for reference (not the test reference) rather than scroll through the tests.

It may shock you to learn that I am in fact a javadoc guy (in fact I'm collecting articles for my undergraduate paper - feel free to message me with anything you've got ^^). It's just that I've seen so much bad documentation that I don't believe it works. Apart from Oracles's Java SE API javadocs nothing even comes close! This may very well be due to the fact that their requirements are set in stone beforehand and they can simply write the specs in the docs, where programmers later add their code. An honourable mention can perhaps go to [World-Wind](https://github.com/nasa/World-Wind-Java/blob/master/). 

Another thing I'd like to point out is that the amount of documentation required reduces with improved quality of object oriented code/design (the same is apparently true for unit tests according to David West, who even went as far as to say that if the design is done right then the tests are redundant; I can't remember where exactly he said that anymore). If your classes are immutable, you don't have to write much about thread safety or possible method side-effects that could potentially affect object state.

**Comment by pa9ey** [comment]
For full disclosure, I'm slowly relenting and coming round a little bit (with caveats) to the usefulness of these comments, _if they're respected and well written_. Having to sit and think of decent comments forces you to seriously question all the classes you've just written! (But of course, as @Glusk2 points out, Qulice doesn't guarantee this, it just maybe draws attention to it for the people who care.)

I've realised that the real point here is, or should be, that **requiring Javadoc comments on test classes is the truly redundant thing**. If you can't get everything you need into the test name then you've almost certainly written a bad test. Or a bad class. Or both.

(Although, related to this, I therefore don't think that test names should be limited to 80 columns. Long names are sometimes required and, seeing as you never call test methods yourself, they effectively act as comments on their own.)

**Comment by yegor256** [comment]
@krzyk I think we need them, no matter what. Java doesn't have any other mechanism of code documenting. That's the best we have and we need to enforce it, both for methods and attributes.

**Comment by 0crat** [comment]
Oops! Job `gh:teamed/qulice#824` was not in scope
