### ISSUE TITLE
LineLenght of 80 characters

### ISSUE THREAD

**Issue by neonailol** [teamed/qulice#862]
What is the reason for this limitation?
Doubling it to 160 would be perfect, i believe this size can fit into any modern developer environment.
For example, my ide with this limitation looks like this, there is a lot of blank space left
![image](https://user-images.githubusercontent.com/440768/34729868-df9d3258-f56e-11e7-855b-6975c9063fb4.png)

**Comment by 0crat** [comment]
@krzyk please, pay attention to this issue

**Comment by krzyk** [comment]
@neonailol It depends, if you have 80 char limit you are somehow forced to split your methods into smaller ones with less blocks because you will hit the limit too soon.
On the other hand I think that a limit of 120 is still healthy.

But on this one I would refer to @yegor256 What's your opinion on increasing the LineLength check to 120 characters?

**Comment by krzyk** [comment]
@yegor256 Similar issue in #867, we have different line length requirements for groovy (which is 120 chars), could we also extend java line lenght to 120 chars?

**Comment by krzyk** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@krzyk what about Git/GitHub split review mode:

<img width="1425" alt="screen shot 2018-05-06 at 7 56 48 am" src="https://user-images.githubusercontent.com/526301/39670014-1c3be44e-5103-11e8-81a9-ac98517e6e94.png">

**Comment by krzyk** [comment]
@yegor256 Well, that depends on the font size, e.g. for me it wraps at 75 (I like bigger fonts :).
If I reset the zoom level I can get 110 chars in line without wrapping (I have 16:9 screen, full hd).

It is harder to test in IntelliJ (split view), because I don't remember what is the default font and size of it.

**Comment by yegor256** [comment]
@krzyk good point about IntelliJ, try to use "Git merge" mode with three columns and you will understand why 80-chars is a good limitation :)

**Comment by krzyk** [comment]
@yegor256 OK, nothing can beat three way merge :)
@neonailol Please close this issue, you can see discussion above why.

**Comment by yegor256** [comment]
@neonailol good points, but we also have some arguments (above). So, one side has to win, while the other one has to lose. This time you lose :)

**Comment by krzyk** [comment]
@neonailol this has been fixed in https://github.com/teamed/qulice/issues/867 please close this issue

**Comment by 0crat** [comment]
Job `gh:teamed/qulice#862` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
